### ISSUE TITLE
Hyphens in Node Names

### ISSUE THREAD

**Issue by slanden** [pdml-lang/basic-specification#5]
The article [Suggestion For a Better XML/HTML Syntax](https://pdml-lang.github.io/docs/suggestion-for-better-xml-html/index.html#ch__18) states in the section titled _Comments_
> an element name cannot contain hyphens (-).

Does this mean hyphens aren't allowed in the middle of names either?

```
[- Comment -]
[custom-element
  some text
]
```

Today's HTML component authors must use multi-word names separated by hyphens to not conflict with any official HTML single-word element, existing or not.

How does this come into play in PDML, especially if used as an alternative to write Web documents?

**Comment by pdml-lang** [comment]
> an element name cannot contain hyphens (-)

This is actually a mistake in the article. Thanks for pointing this out. I have [fixed it](https://pdml-lang.github.io/docs/suggestion-for-better-xml-html/index.html#ch__18). It now states:

"an element name cannot *start with a hyphen* (-)"

> Does this mean hyphens aren't allowed in the middle of names either?

They _are_ allowed in the middle of names. They are just not allowed as a first character of a name.

The official [PDML specification](https://pdml-lang.github.io/docs/basic-specification/index.html#node_name) states:

"A node name must match the regex `[a-zA-Z_][a-zA-Z0-9_\.-]*`. This means that a name starts with a letter or an underscore (`_`), optionally followed by any number of letters, digits, underscores (`_`), hyphens (`-`), or dots (`.`)."

> How does this come into play in PDML, especially if used as an alternative to write Web documents?

The PDML/PML rule for names is the same as the rule in [XML/HTML](https://www.w3schools.com/xml/xml_elements.asp) (see chapter 'XML Naming Rules'):

> XML elements must follow these naming rules:
> -  Element names are case-sensitive
> -  Element names must start with a letter or underscore
> -  Element names cannot start with the letters xml (or XML, or Xml, etc)
> -  Element names can contain letters, digits, hyphens, underscores, and periods
> -  Element names cannot contain spaces
